### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TransNet:

### ISSUE THREAD

**Issue by Xu-J-Yan** [miccaiif/TransMEF#22]
RuntimeError: Error(s) in loading state_dict for TransNet:
	Missing key(s) in state_dict: "encoder.inc.double_conv.0.weight", "encoder.inc.double_conv.0.bias", 

作者您好，我在复现项目的时候遇到了这个问题，请问应该怎么解决呢。

**Comment by miccaiif** [comment]
> RuntimeError: Error(s) in loading state_dict for TransNet: Missing key(s) in state_dict: "encoder.inc.double_conv.0.weight", "encoder.inc.double_conv.0.bias",
> 
> 作者您好，我在复现项目的时候遇到了这个问题，请问应该怎么解决呢。

您好，您这个问题应该是导入模型的问题。可参考以下引导进行问题排除：

Error loading pretrained model.

There are two points to note. 1) Please check the downloaded models, as many errors for the models are caused by download problems. 2) Please do not change the argument '--gpus' in the argparse at the beginning of the code. Its default value is '0,1', which means the provided model was trained using two gpus. Changing this value will cause errors in loading model parameters.
